"""create tables

Revision ID: 747194e00b44
Revises: 
Create Date: 2026-02-11 23:54:50.719415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747194e00b44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_key'), 'roles', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='usergender'), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEED_VERIFICATION', 'SUSPENDED', 'REJECTED', 'PENDING', name='user_status'), nullable=False),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('two_fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_fa_secret', sa.String(length=32), nullable=True),
    sa.Column('two_fa_method', sa.String(length=20), nullable=True),
    sa.Column('two_fa_backup_codes', sa.JSON(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_user_agent', sa.String(length=500), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trusted_devices', sa.JSON(), nullable=True),
    sa.Column('fcm_tokens', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('total_donations', sa.Float(), nullable=True),
    sa.Column('donations_count', sa.Integer(), nullable=True),
    sa.Column('total_sponsored', sa.Float(), nullable=True),
    sa.Column('sponsored_count', sa.Integer(), nullable=True),
    sa.Column('total_needs', sa.Integer(), nullable=True),
    sa.Column('completed_needs', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('badge_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_users_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('national_id', name=op.f('uq_users_national_id')),
    sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_charities_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charities')),
    sa.UniqueConstraint('uuid', name=op.f('uq_charities_uuid'))
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('shop_type', sa.Enum('individual', 'company', 'charity_shop', name='shop_type'), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_shops_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shops')),
    sa.UniqueConstraint('uuid', name=op.f('uq_shops_uuid'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('charity_followers',
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_charity_followers_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_charity_followers_user_id_users')),
    sa.PrimaryKeyConstraint('charity_id', 'user_id', name=op.f('pk_charity_followers'))
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discount_type'), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=True),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('user_ids', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_coupons_charity_id_charities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name=op.f('uq_coupons_code'))
    )
    op.create_table('need_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('collected_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('linked_product_ids', sa.JSON(), nullable=True),
    sa.Column('progress_display_settings', sa.JSON(), nullable=True),
    sa.Column('verified_by_list', sa.JSON(), nullable=True),
    sa.Column('campaign_settings', sa.JSON(), nullable=True),
    sa.Column('social_sharing', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('verified_badge', sa.Boolean(), nullable=True),
    sa.Column('badge_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'active', 'completed', 'cancelled', name='need_status'), nullable=True),
    sa.Column('category', sa.Enum('medical', 'education', 'housing', 'food', 'clothing', 'debt', 'other', 'emergency', 'natural_disaster', name='need_category'), nullable=True),
    sa.Column('privacy_level', sa.Enum('public', 'protected', 'private', name='privacy_level'), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('emergency_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('needy_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_need_ads_charity_id_charities')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_need_ads_created_by_id_users')),
    sa.ForeignKeyConstraint(['needy_user_id'], ['users.id'], name=op.f('fk_need_ads_needy_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_need_ads')),
    sa.UniqueConstraint('uuid', name=op.f('uq_need_ads_uuid'))
    )
    op.create_table('shop_vendors',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_shop_vendors_shop_id_shops'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shop_vendors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shop_id', 'user_id', name=op.f('pk_shop_vendors'))
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'abandoned', 'converted', 'expired', name='cart_status'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('charity_amount', sa.Float(), nullable=True),
    sa.Column('donation_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_carts_charity_id_charities')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_carts_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_carts_need_id_need_ads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('uuid', name=op.f('uq_carts_uuid'))
    )
    op.create_table('donor_commitments',
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('committed_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_donor_commitments_donor_id_users')),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_donor_commitments_need_id_need_ads')),
    sa.PrimaryKeyConstraint('donor_id', 'need_id', name=op.f('pk_donor_commitments'))
    )
    op.create_table('need_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_need_comments_need_id_need_ads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_need_comments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_need_comments'))
    )
    op.create_index(op.f('ix_need_comments_need_id'), 'need_comments', ['need_id'], unique=False)
    op.create_index(op.f('ix_need_comments_user_id'), 'need_comments', ['user_id'], unique=False)
    op.create_table('need_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('charity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verification_status'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_need_verifications_charity_id_charities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_need_verifications_need_id_need_ads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_need_verifications'))
    )
    op.create_index(op.f('ix_need_verifications_charity_id'), 'need_verifications', ['charity_id'], unique=False)
    op.create_index(op.f('ix_need_verifications_need_id'), 'need_verifications', ['need_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status'), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'partially_refunded', name='payment_status'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('charity_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('shipping_method', sa.Enum('standard', 'express', 'courier', 'store_pickup', name='shipping_method'), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('shipping_city', sa.String(length=100), nullable=False),
    sa.Column('shipping_province', sa.String(length=100), nullable=False),
    sa.Column('shipping_postal_code', sa.String(length=20), nullable=True),
    sa.Column('shipping_tracking_code', sa.String(length=100), nullable=True),
    sa.Column('shipping_carrier', sa.String(length=50), nullable=True),
    sa.Column('shipping_notes', sa.Text(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_province', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_details', sa.JSON(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_orders_charity_id_charities')),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_orders_coupon_id_coupons')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_orders_customer_id_users')),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_orders_need_id_need_ads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number')),
    sa.UniqueConstraint('uuid', name=op.f('uq_orders_uuid'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('charity_percentage', sa.Float(), nullable=True),
    sa.Column('charity_fixed_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'active', 'sold_out', 'archived', name='product_status'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_products_charity_id_charities')),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_products_need_id_need_ads')),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name=op.f('fk_products_shop_id_shops')),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], name=op.f('fk_products_vendor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('uuid', name=op.f('uq_products_uuid'))
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('charity_percentage', sa.Float(), nullable=True),
    sa.Column('charity_fixed_amount', sa.Float(), nullable=True),
    sa.Column('charity_total', sa.Float(), nullable=True),
    sa.Column('donation_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_cart_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items'))
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.Enum('direct_transfer', 'court', 'digital_wallet', 'bank_gateway', 'product_sale', name='payment_method'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'refunded', name='donation_status'), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('donor_ip', sa.String(length=45), nullable=True),
    sa.Column('donor_user_agent', sa.Text(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('need_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_donations_charity_id_charities')),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], name=op.f('fk_donations_donor_id_users')),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_donations_need_id_need_ads')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_donations_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations')),
    sa.UniqueConstraint('uuid', name=op.f('uq_donations_uuid'))
    )
    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('previous_quantity', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('adjustment', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_history_created_by_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_history_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_history'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('charity_percentage', sa.Float(), nullable=True),
    sa.Column('charity_fixed_amount', sa.Float(), nullable=True),
    sa.Column('charity_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_table('product_need_association',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('need_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('donation_amount', sa.Float(), nullable=True),
    sa.Column('charity_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['need_id'], ['need_ads.id'], name=op.f('fk_product_need_association_need_id_need_ads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_need_association_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'need_id', name=op.f('pk_product_need_association'))
    )
    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'processed', name='return_status'), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_method', sa.String(length=50), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_return_requests_customer_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_return_requests_order_id_orders')),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_return_requests_processed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_requests')),
    sa.UniqueConstraint('uuid', name=op.f('uq_return_requests_uuid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_requests')
    op.drop_table('product_need_association')
    op.drop_table('order_items')
    op.drop_table('inventory_history')
    op.drop_table('donations')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_index(op.f('ix_need_verifications_need_id'), table_name='need_verifications')
    op.drop_index(op.f('ix_need_verifications_charity_id'), table_name='need_verifications')
    op.drop_table('need_verifications')
    op.drop_index(op.f('ix_need_comments_user_id'), table_name='need_comments')
    op.drop_index(op.f('ix_need_comments_need_id'), table_name='need_comments')
    op.drop_table('need_comments')
    op.drop_table('donor_commitments')
    op.drop_table('carts')
    op.drop_table('shop_vendors')
    op.drop_table('need_ads')
    op.drop_table('coupons')
    op.drop_table('charity_followers')
    op.drop_table('user_roles')
    op.drop_table('shops')
    op.drop_table('role_permissions')
    op.drop_table('charities')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_key'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
